-- Create the vessels table with your exact specification
CREATE TABLE public.vessels (
  id serial NOT NULL,
  name character varying(255) NOT NULL,
  mmsi character varying(20) NULL,
  imo character varying(20) NULL,
  vessel_type character varying(100) NULL,
  flag character varying(100) NULL,
  built integer NULL,
  deadweight integer NULL,
  cargo_capacity integer NULL,
  current_lat numeric(10, 8) NULL,
  current_lng numeric(11, 8) NULL,
  speed character varying(20) NULL,
  status character varying(100) NULL,
  departure_port integer NULL,
  destination_port integer NULL,
  departure_date timestamp without time zone NULL,
  arrival_date timestamp without time zone NULL,
  eta timestamp without time zone NULL,
  company_id integer NULL,
  cargo_type character varying(100) NULL,
  cargo_quantity integer NULL,
  oil_source character varying(100) NULL,
  route_info text NULL,
  metadata jsonb NULL,
  created_at timestamp with time zone NULL DEFAULT now(),
  updated_at timestamp with time zone NULL DEFAULT now(),
  departure_lat numeric(10, 6) NULL,
  departure_lng numeric(10, 6) NULL,
  destination_lat numeric(10, 6) NULL,
  destination_lng numeric(10, 6) NULL,
  buyer_name text NULL DEFAULT 'NA'::text,
  seller_name text NULL,
  owner_name text NULL,
  operator_name text NULL,
  last_updated timestamp without time zone NULL DEFAULT CURRENT_TIMESTAMP,
  current_region text NULL,
  oil_type text NULL,
  quantity numeric(15, 2) NULL,
  deal_value numeric(15, 2) NULL,
  loading_port text NULL,
  price numeric(15, 2) NULL,
  market_price numeric(15, 2) NULL,
  source_company text NULL,
  target_refinery text NULL,
  shipping_type text NULL,
  route_distance numeric(10, 2) NULL,
  callsign text NULL,
  course integer NULL,
  nav_status text NULL,
  draught numeric(5, 2) NULL,
  length numeric(8, 2) NULL,
  width numeric(6, 2) NULL,
  engine_power integer NULL,
  fuel_consumption numeric(8, 2) NULL,
  crew_size integer NULL,
  gross_tonnage integer NULL,
  dealvalue text NULL,
  marketprice text NULL,
  routedistance text NULL,
  currentport text NULL,
  vesselstatus text NULL,
  destination text NULL,
  beam text NULL,
  draft text NULL,
  CONSTRAINT vessels_pkey PRIMARY KEY (id),
  CONSTRAINT vessels_imo_key UNIQUE (imo),
  CONSTRAINT vessels_mmsi_key UNIQUE (mmsi),
  CONSTRAINT vessels_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies (id),
  CONSTRAINT vessels_departure_port_fkey FOREIGN KEY (departure_port) REFERENCES ports (id),
  CONSTRAINT vessels_destination_port_fkey FOREIGN KEY (destination_port) REFERENCES ports (id)
) TABLESPACE pg_default;