-- Convert ports table to use integer ID
-- First backup the existing ports data
CREATE TABLE ports_uuid_backup AS SELECT * FROM ports;

-- Create new ports table with integer ID and copy essential data
DROP TABLE ports CASCADE;
CREATE TABLE public.ports (
  id serial PRIMARY KEY,
  name text,
  country text,
  region text,
  port_type text,
  description text,
  facilities text,
  type text,
  status text,
  city text,
  timezone text,
  port_authority text,
  operator text,
  owner text,
  email text,
  phone text,
  website text,
  address text,
  postal_code text,
  operating_hours text,
  services text,
  cargo_types text,
  security_level text,
  environmental_certifications text,
  tug_assistance boolean,
  lat numeric,
  lng numeric,
  capacity bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_updated timestamp with time zone,
  annual_throughput bigint,
  max_vessel_length numeric,
  max_vessel_beam numeric,
  max_draught numeric,
  max_deadweight bigint,
  berth_count integer,
  terminal_count integer,
  channel_depth numeric,
  berth_depth numeric,
  anchorage_depth numeric,
  pilotage_required boolean,
  established integer,
  total_cargo bigint,
  vessel_count integer,
  port_charges numeric,
  tidal_range numeric,
  average_wait_time numeric,
  airport_distance numeric,
  road_connection boolean,
  rail_connection boolean,
  free_trade_zone boolean,
  customs_office boolean,
  quarantine_station boolean,
  photo text,
  nearby_ports text,
  connected_refineries text,
  currency text,
  weather_restrictions text,
  next_inspection date,
  last_inspection date
);

-- Copy data from backup (without the old UUID IDs)
INSERT INTO ports (
  name, country, region, port_type, description, facilities, type, status, city, 
  timezone, port_authority, operator, owner, email, phone, website, address, 
  postal_code, operating_hours, services, cargo_types, security_level, 
  environmental_certifications, tug_assistance, lat, lng, capacity, created_at, 
  updated_at, last_updated, annual_throughput, max_vessel_length, max_vessel_beam, 
  max_draught, max_deadweight, berth_count, terminal_count, channel_depth, 
  berth_depth, anchorage_depth, pilotage_required, established, total_cargo, 
  vessel_count, port_charges, tidal_range, average_wait_time, airport_distance, 
  road_connection, rail_connection, free_trade_zone, customs_office, 
  quarantine_station, photo, nearby_ports, connected_refineries, currency, 
  weather_restrictions, next_inspection, last_inspection
)
SELECT 
  name, country, region, port_type, description, facilities, type, status, city, 
  timezone, port_authority, operator, owner, email, phone, website, address, 
  postal_code, operating_hours, services, cargo_types, security_level, 
  environmental_certifications, tug_assistance, lat, lng, capacity, created_at, 
  updated_at, last_updated, annual_throughput, max_vessel_length, max_vessel_beam, 
  max_draught, max_deadweight, berth_count, terminal_count, channel_depth, 
  berth_depth, anchorage_depth, pilotage_required, established, total_cargo, 
  vessel_count, port_charges, tidal_range, average_wait_time, airport_distance, 
  road_connection, rail_connection, free_trade_zone, customs_office, 
  quarantine_station, photo, nearby_ports, connected_refineries, currency, 
  weather_restrictions, next_inspection, last_inspection
FROM ports_uuid_backup;